### ISSUE TITLE
rust-analyzer with VSCode doesn't seem to work with riff shell?

### ISSUE THREAD

**Issue by XFFXFF** [DeterminateSystems/riff#126]
OS: wsl2 (ubuntu 22.04)  

Riff version: 1.0.0  

Things I tried to run: `riff shell` and then open VSCode from the shell  

![image](https://user-images.githubusercontent.com/30254428/189505488-54bbc935-d57b-4909-9c05-37ad1a1fde98.png)

it gets an error  like

![image](https://user-images.githubusercontent.com/30254428/189505508-bc8e671a-cc16-4eca-b458-afc53e41044a.png)

I got the same error a few days ago when trying to use nix, which was fixed by adding `rust-src` to extensions.

```nix
{ nixpkgs ? import <nixpkgs> { }}:

let
  rustOverlay = builtins.fetchTarball "https://github.com/oxalica/rust-overlay/archive/master.tar.gz";
  pkgs = import <nixpkgs> {
    overlays = [ (import rustOverlay) ];
  };
in
  pkgs.mkShell {
    buildInputs = with pkgs; [
    (pkgs.rust-bin.stable.latest.default.override {
          extensions = [ "rust-src" "cargo" "rustc" ];
    })
    ];

    RUST_BACKTRACE = 1;
  }
```

**Comment by cole-h** [comment]
Could you try my PR at https://github.com/DeterminateSystems/riff/pull/171 and see if this fixes it for you? There are instructions in the PR body, but I'm happy to help further if they are unclear.

If `rust-analyzer` works for you outside of `riff shell`, this PR should make it work for you inside as well.

**Comment by XFFXFF** [comment]
@cole-h Yes, it works for me. But it uses the rustc I installed on my system, not the nix store.

**Comment by cole-h** [comment]
That is to be expected. Is this undesirable for you?

The idea is to rely on the user's Rust setup so that any configuration that has been done (e.g. in order to get rust-analyzer working) will be carried over with ease. This also means it's easy to support `rust-toolchain.toml` files (like in https://github.com/DeterminateSystems/riff/issues/147), because the user-installed `rustup` will handle that for us.

**Comment by XFFXFF** [comment]
This is ok for me. Thanks for the explanation @cole-h , I originally thought that riff uses the `rustc` installed by nix like other tools like `cargo2nix`
